Finished required tools installations sections.

diff --git a/bb-recon-automation b/bb-recon-automation
--- a/bb-recon-automation
+++ b/bb-recon-automation
@@ -9,7 +9,7 @@ set -euo pipefail
 
 
 ### Configuration ###
-pd_dependencies=("go" "masscan" "nmap")
+tools_dependencies=("go" "masscan" "nmap")
 pd_tools=("subfinder" "shuffledns" "alterx" "dnsx" "naabu" "httpx" "katana")
 
 
@@ -17,73 +17,82 @@ pd_tools=("subfinder" "shuffledns" "alterx" "dnsx" "naabu" "httpx" "katana")
 
 ### Functions ###
 
-# Check if required Project Discovery tools are installed.
-check_pd_required_tools() {
-echo -e "\nChecking if required tools are installed.\n"
+# Check if script tools are isntalled.
+check_script_tools() {
+echo -e "\n[INF] Checking if required tools are installed."
 
-for tool in "${pd_required_tools[@]}"; do
+for tool in "${pd_tools[@]}"; do
     if command -v "$tool" &> /dev/null; then
-        echo "Tool: $tool is already installed."
+        echo "[INF] $tool is already installed."
         continue
     else
-        echo "Warning: $tool is not installed."
+        echo "[WRN] $tool is not installed."
     fi
 done
 }
 
-# Check if prerequirements for PDTM are met.
-check_pd_dependecies() {
-echo -e "\nChecking if Project Discovery dependencies are met.\n"
-
-for tool in "${pd_dependencies[@]}"; do
+# Check and install go, nmap, masscan and massdns.
+install_tools_dependencies() {
+for tool in "${tools_dependencies[@]}"; do
     if command -v "$tool" &>/dev/null; then
-        echo "$tool is already installed."
+        echo "[INF] $tool is already installed."
         continue
-    else
-        echo "Warning: $tool is not installed."
     fi
-done
-}
 
-
-# Install prerequired tools
-install_pd_dependencies() {
-    for tool in "${pd_dependencies[@]}"; do
-        if command -v "$tool" &>/dev/null; then
-            echo "$tool is already installed."
-            continue
-        fi
-        
-        echo "Installing $tool..."
-        
+    echo "[INF] Installing $tool..."
         if command -v apt &>/dev/null; then
             sudo apt update && sudo apt install -y "$tool"
         elif command -v pacman &>/dev/null; then
             sudo pacman -S --noconfirm "$tool"
         else
-            echo "Error: No supported package manager found. Please install manually."
+            echo "[ERR] No package manager found for $tool."
             return 1
         fi
-
-        if command -v "$tool" &>/dev/null; then
-            echo "$tool was installed successfully."
-        else
-            echo "Failed to install $tool."
+        
+        if ! command -v "$tool" &>/dev/null; then
+            echo "[ERR] Failed to install $tool."
             return 1
         fi
     done
+
+
+    if command -v massdns &>/dev/null; then
+        echo "[INF] massdns is already installed."
+    else
+        echo "[INF] Installing massdns from source..."
+        local tmp_dir=$(mktemp -d)
+        if git clone https://github.com/blechschmidt/massdns.git "$tmp_dir/massdns"; then
+            (
+                cd "$tmp_dir/massdns" && 
+                make && 
+                sudo cp bin/massdns /usr/local/bin/massdns
+            )
+            local status=$?
+            rm -rf "$tmp_dir"
+            
+            if [ $status -eq 0 ]; then
+                echo "[INF] massdns was installed successfully."
+            else
+                echo "[ERR] Failed to compile massdns."
+                return 1
+            fi
+        else
+            echo "[ERR] Failed to clone massdns repository."
+            return 1
+        fi
+    fi 
 }
 
-# Install required tools
+# Install PDTM
 install_pdtm() {
     if command -v pdtm &>/dev/null; then
-        echo "PDTM is already installed!"
+        echo "[INF] PDTM is already installed."
         return 0
     fi
     
-    echo "Checking if go is correctly set on \$PATH"
+    echo "[INF] Checking if go is correctly set on \$PATH"
     if [[ ! "$PATH" =~ "/go/bin" ]]; then
-        echo "go path is not part of the \$PATH. Adding it now through ~/.bashrc"
+        echo "[INF] go path is not part of the \$PATH. Adding it now through ~/.bashrc"
         cat << 'EOF' >> "$HOME/.bashrc"
 export GOPATH="$HOME/go"
 export PATH="$PATH:$GOPATH/bin"
@@ -92,35 +101,86 @@ EOF
     export GOPATH="$HOME/go"
     export PATH="$PATH:$GOPATH/bin"
     else
-        echo "Go path is already present."
+        echo "[INF] Go path is already present."
     fi
 
-    echo "Installing PDTM (Project Discovery Tool Manager)"
+    echo "[INF] Installing PDTM (Project Discovery Tool Manager)"
     go install -v github.com/projectdiscovery/pdtm/cmd/pdtm@latest
 
     if [[ $? -eq 0 ]]; then
-        echo "SUCCESS! PDTM is now installed."
+        echo "[INF] PDTM is now installed."
     else
-        echo "ERROR: Failed to install PDTM."
+        echo "[ERR] Failed to install PDTM."
         return 1
     fi
 }
 
-install_pd_tools() {
-    
-    echo "Installing required tools..."
-    # pdtm -ia -igp
+# Install script tools
+install_script_tools() {
+    echo -e "\n[INF] Installing required tools..."
+    pdtm -i subfinder,shuffledns,alterx,dnsx,naabu,httpx,katana -igp
 
+    if [[ $? -eq 0 ]]; then
+        echo "[INF] All required tools were installed."
+    else
+        echo "[ERR] Failed to install required tools."
+        return 1
+    fi
 }
+
 
 ### Main Logic ###
 
+# Flags options
+install_tools=()
+verbose=false
 
+while getopts ":i:vh" opt; do
+    case $opt in
+        i)
+            if [[ "$OPTARG" == "pdtm" || "$OPTARG" == "tools" ]]; then
+                install_tools+=("$OPTARG")
+            else
+                echo "Error: Invalid argument for -i. Use 'pdtm' or 'tools'." >&2
+            fi
+            ;;
+        v) verbose=true ;;
+        h)
+            echo "Usage: $0 [-i pdmt] [-i tools] [-v verbose] [-h help]"
+            exit 0
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND-1))
 
+if [[ ${#install_tools[@]} -eq 0 ]]; then
+    echo -e "\n[WRN] No option was specified via -i. Skipping installation."
+fi
+
+for task in "${install_tools[@]}"; do
+    case "$task" in
+        "pdtm")
+            echo -e "[INF] Starting PDTM installation sequence...\n"
+            install_tools_dependencies
+            install_pdtm
+            ;;
+        "tools")
+            echo "\n[INF] INFStarting tools installation...\n"
+            check_script_tools
+            install_script_tools
+            ;;
+    esac
+done
+
+[[ $verbose == true ]] && set -x
 
 ####################### TEXT WALL #######################
-echo -e "This script uses Project Discovery tools to perform each task. Before starting, make sure you have installed the required tools in your system."
-echo -e "You can install them through PDTM (Project Discovery's Tool Manager), Use [-i pdtm] to install PDTM or use [-i tools] to install them through "
-echo -e "PDTM"
+#echo -e "This script uses Project Discovery tools to perform each task. Before starting, make sure you have installed the required tools in your system."
+#echo -e "You can install them through PDTM (Project Discovery's Tool Manager), Use [-i pdtm] to install PDTM or use [-i tools] to install them through "
+#echo -e "PDTM"
 
 
